//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidHW
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD
    {
        public int 訂單ID { get; set; }
        public string 訂購電話 { get; set; }
        public Nullable<int> 雞排_份 { get; set; }
        public Nullable<int> 鹹酥雞_份 { get; set; }
        public Nullable<int> 雞心_串 { get; set; }
        public Nullable<int> 雞胗_串 { get; set; }
        public Nullable<int> 雞屁股_串 { get; set; }
        public Nullable<int> 甜不辣_份 { get; set; }
        public Nullable<int> 薯條_份 { get; set; }
        public Nullable<int> 季節蔬菜_份 { get; set; }
        public string 辣度 { get; set; }
        public Nullable<bool> 外送 { get; set; }
        public Nullable<int> 總金額 { get; set; }
        public Nullable<System.DateTime> 訂單時間 { get; set; }
        public Nullable<bool> 訂單狀態 { get; set; }
    }
}
